services:
  web:
    build: .
    container_name: enfekte_web
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: gunicorn -b 0.0.0.0:8000 app:app --workers=2 --timeout=90

